name: Practice Github Actions
on:
  workflow_dispatch:

jobs:
  build:
    name: Build lfact
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          python3 -m pip install flit wheel

      - name: Build the project
        working-directory: lfact
        run: |
          flit build


