name: Practice Github Actions
on:
  workflow_dispatch:

jobs:
  build:
    name: Build lfact
    runs-on: ubuntu-latest

    steps:

      - name: checkout source code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install flit wheel

      - name: Build the project
        run: |
          pwd
          flit build


