name: Practice Github Actions
on:
  workflow_dispatch:

jobs:
  build:
    name: Build lfact
    runs-on: ubuntu-latest

    steps:

      - name: checkout source code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install flit wheel

      - name: Build the project
        run: |
          flit build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: lfact-files
          path: dist/*


  upload:
    needs: build
    name: Upload arrtifact to PyPI
    runs-on: ubuntu-latest

    steps:

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: lfact-files
          path: dist/

      - name: Display structure of downloaded files
        run: ls -R





